name: ci-sonarqube
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout
        uses: actions/checkout@v2

      - name: Run Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run Test          
        run: go test -coverprofile=coverage.out

      - name: Run Analisys
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: http://ec2-54-196-178-167.compute-1.amazonaws.com
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}